language: go

sudo: required

services:
  - docker

go:
  - 1.11.x
  - 1.12.x

before_script:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - go mod vendor
  - go generate
  - go fmt -s ./...
  - git add .
  - git diff --cached
  - git diff-index --cached --exit-code HEAD

script:
  - ./coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
