language: go

sudo: required

services:
  - docker

go:
  - 1.11.x
  - 1.12.x

before_script:
  - GO111MODULE=on go mod vendor
  - GO111MODULE=on go generate
  - GO111MODULE=on go fmt ./...
  - git add .
  - git diff --cached
  - git diff-index --cached --exit-code HEAD

script:
  - ./coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
